'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default1
    
    '''<summary>
    '''WelcomeBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WelcomeBox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TotalOCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalOCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SexCountSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SexCountSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MastCountSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MastCountSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AvgO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvgO As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
